apiVersion: v1
kind: Pod
metadata:
  name: podName
  namespace: namespace
  annotations:
    attackType: "attack"
    duration: xDration # duration of the attack
    start: xStart # start at the x minute of the experiment
spec:
  nodeName: nodeName
  containers:
  - name: pod
    image: podImage
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: memoryLimit
        cpu: cpuLimit
      requests: 
        memory: memoryRequests
        cpu: cpuRequests
    
    
